### ISSUE TITLE
List creation

### ISSUE THREAD

**Issue by gabrc52** [sipb/svelte-moira#12]
Given that not even WebMoira cannot do that without taking you to a separate page to create a list, it might actually be *impossible* to create a list. 2 alternatives:

1. Create a bunch of pre-created lists and when someone "creates" a list, rename one of them and set the properties using the daemon keytab. (Needs active maintenance, or creating a big amount of lists).
2. Embed listmaker.mit.edu as a "popup" which would be actually an iframe. When the user creates a list, refresh their list of lists and take them to the list which was just created (by comparing before and after).

**Comment by dtemkin1** [comment]
I tried doing this as an modal/iframe, but I think since this isn't an IS&T registered application it runs into issues. This may be possible in the future though.

<img width="1128" alt="image" src="https://github.com/sipb/svelte-moira/assets/65834932/17a2f0a4-0a5b-4362-8a1f-67179dcc03e2">

**Comment by gabrc52** [comment]
I think it does let you embed it from within other mit.edu sites

**Comment by dtemkin1** [comment]
:o good to know slayy
